# Generated by Django 3.2.5 on 2021-07-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Dealer name')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=10, verbose_name="Car's brand")),
                ('model', models.CharField(max_length=10, verbose_name="Car's model")),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealer', verbose_name="Car's dealer")),
            ],
        ),
    ]
